lib: [
  "_build/install/default/lib/GTLC/AST.ml"
  "_build/install/default/lib/GTLC/GTLC.a"
  "_build/install/default/lib/GTLC/GTLC.cma"
  "_build/install/default/lib/GTLC/GTLC.cmxa"
  "_build/install/default/lib/GTLC/GTLC.ml"
  "_build/install/default/lib/GTLC/META"
  "_build/install/default/lib/GTLC/aST.cmi"
  "_build/install/default/lib/GTLC/aST.cmt"
  "_build/install/default/lib/GTLC/aST.cmx"
  "_build/install/default/lib/GTLC/dune-package"
  "_build/install/default/lib/GTLC/gTLC.cmi"
  "_build/install/default/lib/GTLC/gTLC.cmt"
  "_build/install/default/lib/GTLC/gTLC.cmx"
  "_build/install/default/lib/GTLC/lexer.cmi"
  "_build/install/default/lib/GTLC/lexer.cmt"
  "_build/install/default/lib/GTLC/lexer.cmx"
  "_build/install/default/lib/GTLC/lexer.ml"
  "_build/install/default/lib/GTLC/opam"
  "_build/install/default/lib/GTLC/parser.cmi"
  "_build/install/default/lib/GTLC/parser.cmt"
  "_build/install/default/lib/GTLC/parser.cmti"
  "_build/install/default/lib/GTLC/parser.cmx"
  "_build/install/default/lib/GTLC/parser.ml"
  "_build/install/default/lib/GTLC/parser.mli"
]
libexec: [
  "_build/install/default/lib/GTLC/GTLC.cmxs"
]
doc: [
  "_build/install/default/doc/GTLC/README.md"
]
